### ISSUE TITLE
GPU Util

### ISSUE THREAD

**Issue by Xixi7301210** [omron-sinicx/soft-robot-sim-to-real#1]
Thanks for your sharing！I have successfully run the "train_policy.py".  However, the GPU utilization rate is very low,  about 2%.  The “device=cuda：0” has been achieved.  Have you encountered this problem？

**Comment by MasashiHamaya** [comment]
@Xixi7301210  Thank you very much for your question! Yes, this is likely because the simulation is based on Mujoco, which relies on CPU, resulting in less GPU utilization.

**Comment by Xixi7301210** [comment]
Thanks a lot!
